/* Generated By:JJTree: Do not edit this line. ASTActivity.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.edu.thss.iise.beehivez.server.index.petrinetindex.rltMatrix.queryParser;

public class ASTActivity extends SimpleNode {
	public ASTActivity(int id) {
		super(id);
	}

	public ASTActivity(Parser p, int id) {
		super(p, id);
	}

	@Override
	public void jjtSetValue(Object o) {
		if (o instanceof String) {
			String s = (String) o;
			if (s.startsWith("\"") && s.endsWith("\"")) {
				value = s.substring(1, s.length() - 1);
			} else
				value = s;
		} else
			value = o;
	}

	public void setValue(String image) {
		// TODO Auto-generated method stub

	}

}
/*
 * JavaCC - OriginalChecksum=9eb3d6646b63ea42cb49c61a010865fe (do not edit this
 * line)
 */
