/* Generated By:JJTree: Do not edit this line. ASTOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.edu.thss.iise.beehivez.server.index.petrinetindex.rltMatrix.queryParser;

public class ASTOr extends SimpleNode {
	public ASTOr(int id) {
		super(id);
	}

	public ASTOr(Parser p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=e46430602b57dd97adcedd2936b20dbf (do not edit this
 * line)
 */
