/* Generated By:JJTree: Do not edit this line. ASTStart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cn.edu.thss.iise.beehivez.server.index.petrinetindex.rltMatrix.queryParser;

public class ASTStart extends SimpleNode {
	public ASTStart(int id) {
		super(id);
	}

	public ASTStart(Parser p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=ff45f35b30383b4cdee3c1635ae2c863 (do not edit this
 * line)
 */
