/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package cn.edu.thss.iise.beehivez.server.index.petrinetindex.rltMatrix.queryParser;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int OP = 5;
	/** RegularExpression Id. */
	int RLT_PARALLEL = 6;
	/** RegularExpression Id. */
	int RLT_DIR_SUCC = 7;
	/** RegularExpression Id. */
	int RLT_INDIR_SUCC = 8;
	/** RegularExpression Id. */
	int RLT_DIR_CASUAL = 9;
	/** RegularExpression Id. */
	int RLT_INDIR_CASUAL = 10;
	/** RegularExpression Id. */
	int RLT_CYCLE = 11;
	/** RegularExpression Id. */
	int RLT_MUTEX = 12;
	/** RegularExpression Id. */
	int AND = 13;
	/** RegularExpression Id. */
	int OR = 14;
	/** RegularExpression Id. */
	int ACTIVITY = 15;

	/** Lexical state. */
	int DEFAULT = 0;

	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"",
			"<OP>", "\"\\u2225\"", "\">\"", "\"\\u00bb\"", "\"\\u2192\"",
			"\"\\u21a0\"", "\"\\u229a\"", "\"\\u00d7\"", "\"and\"", "\"or\"",
			"<ACTIVITY>", "\";\"", "\"(\"", "\")\"", };

}
