/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package cn.edu.thss.iise.beehivez.server.index.petrinetindex.rltMatrix.queryParser;

public interface ParserTreeConstants {
	public int JJTSTART = 0;
	public int JJTVOID = 1;
	public int JJTOR = 2;
	public int JJTAND = 3;
	public int JJTOP = 4;
	public int JJTACTIVITY = 5;

	public String[] jjtNodeName = { "Start", "void", "Or", "And", "Op",
			"Activity", };
}
/*
 * JavaCC - OriginalChecksum=5958d85ee519fa0d58a78acdc861368a (do not edit this
 * line)
 */
