/* Generated By:JavaCC: Do not edit this line. QueryParserTokenManager.java */
package com.chinamobile.bpmspace.core.repository.index.query.queryparser;

/** Token Manager. */
public class QueryParserTokenManager implements QueryParserConstants {

	/** Debug output. */
	public java.io.PrintStream debugStream = System.out;

	/** Set debug output. */
	public void setDebugStream(java.io.PrintStream ds) {
		debugStream = ds;
	}

	private final int jjStopStringLiteralDfa_0(int pos, long active0) {
		switch (pos) {
		case 0:
			if ((active0 & 0x4L) != 0L)
				return 7;
			return -1;
		case 1:
			if ((active0 & 0x4L) != 0L)
				return 6;
			return -1;
		default:
			return -1;
		}
	}

	private final int jjStartNfa_0(int pos, long active0) {
		return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
	}

	private int jjStopAtPos(int pos, int kind) {
		jjmatchedKind = kind;
		jjmatchedPos = pos;
		return pos + 1;
	}

	private int jjMoveStringLiteralDfa0_0() {
		switch (curChar) {
		case 40:
			return jjStopAtPos(0, 11);
		case 41:
			return jjStopAtPos(0, 12);
		case 59:
			return jjStopAtPos(0, 10);
		case 101:
			return jjMoveStringLiteralDfa1_0(0x4L);
		default:
			return jjMoveNfa_0(1, 0);
		}
	}

	private int jjMoveStringLiteralDfa1_0(long active0) {
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			jjStopStringLiteralDfa_0(0, active0);
			return 1;
		}
		switch (curChar) {
		case 120:
			return jjMoveStringLiteralDfa2_0(active0, 0x4L);
		default:
			break;
		}
		return jjStartNfa_0(0, active0);
	}

	private int jjMoveStringLiteralDfa2_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(0, old0);
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			jjStopStringLiteralDfa_0(1, active0);
			return 2;
		}
		switch (curChar) {
		case 105:
			return jjMoveStringLiteralDfa3_0(active0, 0x4L);
		default:
			break;
		}
		return jjStartNfa_0(1, active0);
	}

	private int jjMoveStringLiteralDfa3_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(1, old0);
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			jjStopStringLiteralDfa_0(2, active0);
			return 3;
		}
		switch (curChar) {
		case 115:
			return jjMoveStringLiteralDfa4_0(active0, 0x4L);
		default:
			break;
		}
		return jjStartNfa_0(2, active0);
	}

	private int jjMoveStringLiteralDfa4_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(2, old0);
		try {
			curChar = input_stream.readChar();
		} catch (java.io.IOException e) {
			jjStopStringLiteralDfa_0(3, active0);
			return 4;
		}
		switch (curChar) {
		case 116:
			if ((active0 & 0x4L) != 0L)
				return jjStopAtPos(4, 2);
			break;
		default:
			break;
		}
		return jjStartNfa_0(3, active0);
	}

	static final long[] jjbitVec0 = { 0x1L, 0x0L, 0x0L, 0x0L };
	static final long[] jjbitVec1 = { 0xfffffffffffffffeL, 0xffffffffffffffffL,
			0xffffffffffffffffL, 0xffffffffffffffffL };
	static final long[] jjbitVec3 = { 0x0L, 0x0L, 0xffffffffffffffffL,
			0xffffffffffffffffL };

	private int jjMoveNfa_0(int startState, int curPos) {
		int startsAt = 0;
		jjnewStateCnt = 57;
		int i = 1;
		jjstateSet[0] = startState;
		int kind = 0x7fffffff;
		for (;;) {
			if (++jjround == 0x7fffffff)
				ReInitRounds();
			if (curChar < 64) {
				long l = 1L << curChar;
				do {
					switch (jjstateSet[--i]) {
					case 1:
						if ((0x100002600L & l) != 0L) {
							if (kind > 9)
								kind = 9;
						} else if (curChar == 34)
							jjCheckNAdd(36);
						else if (curChar == 33) {
							if (kind > 8)
								kind = 8;
						} else if (curChar == 38)
							jjstateSet[jjnewStateCnt++] = 19;
						else if (curChar == 45)
							jjstateSet[jjnewStateCnt++] = 11;
						else if (curChar == 35)
							jjstateSet[jjnewStateCnt++] = 9;
						else if (curChar == 61)
							jjstateSet[jjnewStateCnt++] = 0;
						break;
					case 0:
						if (curChar == 61 && kind > 3)
							kind = 3;
						break;
					case 9:
						if (curChar == 35 && kind > 4)
							kind = 4;
						break;
					case 10:
						if (curChar == 35)
							jjstateSet[jjnewStateCnt++] = 9;
						break;
					case 11:
						if (curChar == 62 && kind > 5)
							kind = 5;
						break;
					case 12:
						if (curChar == 45)
							jjstateSet[jjnewStateCnt++] = 11;
						break;
					case 19:
						if (curChar == 38 && kind > 6)
							kind = 6;
						break;
					case 20:
						if (curChar == 38)
							jjstateSet[jjnewStateCnt++] = 19;
						break;
					case 33:
						if (curChar == 33 && kind > 8)
							kind = 8;
						break;
					case 34:
						if ((0x100002600L & l) != 0L && kind > 9)
							kind = 9;
						break;
					case 35:
						if (curChar == 34)
							jjCheckNAdd(36);
						break;
					case 36:
						if ((0xfffffffbffffffffL & l) != 0L)
							jjCheckNAddTwoStates(36, 37);
						break;
					case 37:
						if (curChar == 34 && kind > 13)
							kind = 13;
						break;
					case 43:
						if (curChar == 32)
							jjstateSet[jjnewStateCnt++] = 42;
						break;
					default:
						break;
					}
				} while (i != startsAt);
			} else if (curChar < 128) {
				long l = 1L << (curChar & 077);
				do {
					switch (jjstateSet[--i]) {
					case 1:
						if (curChar == 112)
							jjAddStates(0, 1);
						else if (curChar == 110)
							jjstateSet[jjnewStateCnt++] = 31;
						else if (curChar == 78)
							jjstateSet[jjnewStateCnt++] = 28;
						else if (curChar == 124)
							jjstateSet[jjnewStateCnt++] = 25;
						else if (curChar == 111)
							jjstateSet[jjnewStateCnt++] = 23;
						else if (curChar == 79)
							jjstateSet[jjnewStateCnt++] = 21;
						else if (curChar == 97)
							jjstateSet[jjnewStateCnt++] = 17;
						else if (curChar == 65)
							jjstateSet[jjnewStateCnt++] = 14;
						else if (curChar == 101)
							jjstateSet[jjnewStateCnt++] = 7;
						break;
					case 2:
						if (curChar == 101 && kind > 4)
							kind = 4;
						break;
					case 3:
						if (curChar == 100)
							jjstateSet[jjnewStateCnt++] = 2;
						break;
					case 4:
						if (curChar == 117)
							jjstateSet[jjnewStateCnt++] = 3;
						break;
					case 5:
						if (curChar == 108)
							jjstateSet[jjnewStateCnt++] = 4;
						break;
					case 6:
						if (curChar == 99)
							jjstateSet[jjnewStateCnt++] = 5;
						break;
					case 7:
						if (curChar == 120)
							jjstateSet[jjnewStateCnt++] = 6;
						break;
					case 8:
						if (curChar == 101)
							jjstateSet[jjnewStateCnt++] = 7;
						break;
					case 13:
						if (curChar == 68 && kind > 6)
							kind = 6;
						break;
					case 14:
						if (curChar == 78)
							jjstateSet[jjnewStateCnt++] = 13;
						break;
					case 15:
						if (curChar == 65)
							jjstateSet[jjnewStateCnt++] = 14;
						break;
					case 16:
						if (curChar == 100 && kind > 6)
							kind = 6;
						break;
					case 17:
						if (curChar == 110)
							jjstateSet[jjnewStateCnt++] = 16;
						break;
					case 18:
						if (curChar == 97)
							jjstateSet[jjnewStateCnt++] = 17;
						break;
					case 21:
						if (curChar == 82 && kind > 7)
							kind = 7;
						break;
					case 22:
						if (curChar == 79)
							jjstateSet[jjnewStateCnt++] = 21;
						break;
					case 23:
						if (curChar == 114 && kind > 7)
							kind = 7;
						break;
					case 24:
						if (curChar == 111)
							jjstateSet[jjnewStateCnt++] = 23;
						break;
					case 25:
						if (curChar == 124 && kind > 7)
							kind = 7;
						break;
					case 26:
						if (curChar == 124)
							jjstateSet[jjnewStateCnt++] = 25;
						break;
					case 27:
						if (curChar == 84 && kind > 8)
							kind = 8;
						break;
					case 28:
						if (curChar == 79)
							jjstateSet[jjnewStateCnt++] = 27;
						break;
					case 29:
						if (curChar == 78)
							jjstateSet[jjnewStateCnt++] = 28;
						break;
					case 30:
						if (curChar == 116 && kind > 8)
							kind = 8;
						break;
					case 31:
						if (curChar == 111)
							jjstateSet[jjnewStateCnt++] = 30;
						break;
					case 32:
						if (curChar == 110)
							jjstateSet[jjnewStateCnt++] = 31;
						break;
					case 36:
						jjAddStates(2, 3);
						break;
					case 38:
						if (curChar == 112)
							jjAddStates(0, 1);
						break;
					case 39:
						if (curChar == 104 && kind > 3)
							kind = 3;
						break;
					case 40:
						if (curChar == 116)
							jjstateSet[jjnewStateCnt++] = 39;
						break;
					case 41:
						if (curChar == 105)
							jjstateSet[jjnewStateCnt++] = 40;
						break;
					case 42:
						if (curChar == 119)
							jjstateSet[jjnewStateCnt++] = 41;
						break;
					case 44:
						if (curChar == 108)
							jjstateSet[jjnewStateCnt++] = 43;
						break;
					case 45:
						if (curChar == 101)
							jjstateSet[jjnewStateCnt++] = 44;
						break;
					case 46:
						if (curChar == 108)
							jjstateSet[jjnewStateCnt++] = 45;
						break;
					case 47:
						if (curChar == 108)
							jjstateSet[jjnewStateCnt++] = 46;
						break;
					case 48:
						if (curChar == 97)
							jjstateSet[jjnewStateCnt++] = 47;
						break;
					case 49:
						if (curChar == 114)
							jjstateSet[jjnewStateCnt++] = 48;
						break;
					case 50:
						if (curChar == 97)
							jjstateSet[jjnewStateCnt++] = 49;
						break;
					case 51:
						if (curChar == 101 && kind > 5)
							kind = 5;
						break;
					case 52:
						if (curChar == 100)
							jjstateSet[jjnewStateCnt++] = 51;
						break;
					case 53:
						if (curChar == 101)
							jjstateSet[jjnewStateCnt++] = 52;
						break;
					case 54:
						if (curChar == 99)
							jjstateSet[jjnewStateCnt++] = 53;
						break;
					case 55:
						if (curChar == 101)
							jjstateSet[jjnewStateCnt++] = 54;
						break;
					case 56:
						if (curChar == 114)
							jjstateSet[jjnewStateCnt++] = 55;
						break;
					default:
						break;
					}
				} while (i != startsAt);
			} else {
				int hiByte = (int) (curChar >> 8);
				int i1 = hiByte >> 6;
				long l1 = 1L << (hiByte & 077);
				int i2 = (curChar & 0xff) >> 6;
				long l2 = 1L << (curChar & 077);
				do {
					switch (jjstateSet[--i]) {
					case 1:
						if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 9)
							kind = 9;
						break;
					case 36:
						if (jjCanMove_1(hiByte, i1, i2, l1, l2))
							jjAddStates(2, 3);
						break;
					default:
						break;
					}
				} while (i != startsAt);
			}
			if (kind != 0x7fffffff) {
				jjmatchedKind = kind;
				jjmatchedPos = curPos;
				kind = 0x7fffffff;
			}
			++curPos;
			if ((i = jjnewStateCnt) == (startsAt = 57 - (jjnewStateCnt = startsAt)))
				return curPos;
			try {
				curChar = input_stream.readChar();
			} catch (java.io.IOException e) {
				return curPos;
			}
		}
	}

	static final int[] jjnextStates = { 50, 56, 36, 37, };

	private static final boolean jjCanMove_0(int hiByte, int i1, int i2,
			long l1, long l2) {
		switch (hiByte) {
		case 48:
			return ((jjbitVec0[i2] & l2) != 0L);
		default:
			return false;
		}
	}

	private static final boolean jjCanMove_1(int hiByte, int i1, int i2,
			long l1, long l2) {
		switch (hiByte) {
		case 0:
			return ((jjbitVec3[i2] & l2) != 0L);
		default:
			if ((jjbitVec1[i1] & l1) != 0L)
				return true;
			return false;
		}
	}

	/** Token literal values. */
	public static final String[] jjstrLiteralImages = { "", null,
			"\145\170\151\163\164", null, null, null, null, null, null, null,
			"\73", "\50", "\51", null, };

	/** Lexer state names. */
	public static final String[] lexStateNames = { "DEFAULT", };
	static final long[] jjtoToken = { 0x3dfdL, };
	static final long[] jjtoSkip = { 0x200L, };
	protected JavaCharStream input_stream;
	private final int[] jjrounds = new int[57];
	private final int[] jjstateSet = new int[114];
	protected char curChar;

	/** Constructor. */
	public QueryParserTokenManager(JavaCharStream stream) {
		if (JavaCharStream.staticFlag)
			throw new Error(
					"ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
		input_stream = stream;
	}

	/** Constructor. */
	public QueryParserTokenManager(JavaCharStream stream, int lexState) {
		this(stream);
		SwitchTo(lexState);
	}

	/** Reinitialise parser. */
	public void ReInit(JavaCharStream stream) {
		jjmatchedPos = jjnewStateCnt = 0;
		curLexState = defaultLexState;
		input_stream = stream;
		ReInitRounds();
	}

	private void ReInitRounds() {
		int i;
		jjround = 0x80000001;
		for (i = 57; i-- > 0;)
			jjrounds[i] = 0x80000000;
	}

	/** Reinitialise parser. */
	public void ReInit(JavaCharStream stream, int lexState) {
		ReInit(stream);
		SwitchTo(lexState);
	}

	/** Switch to specified lex state. */
	public void SwitchTo(int lexState) {
		if (lexState >= 1 || lexState < 0)
			throw new TokenMgrError("Error: Ignoring invalid lexical state : "
					+ lexState + ". State unchanged.",
					TokenMgrError.INVALID_LEXICAL_STATE);
		else
			curLexState = lexState;
	}

	protected Token jjFillToken() {
		final Token t;
		final String curTokenImage;
		final int beginLine;
		final int endLine;
		final int beginColumn;
		final int endColumn;
		String im = jjstrLiteralImages[jjmatchedKind];
		curTokenImage = (im == null) ? input_stream.GetImage() : im;
		beginLine = input_stream.getBeginLine();
		beginColumn = input_stream.getBeginColumn();
		endLine = input_stream.getEndLine();
		endColumn = input_stream.getEndColumn();
		t = Token.newToken(jjmatchedKind, curTokenImage);

		t.beginLine = beginLine;
		t.endLine = endLine;
		t.beginColumn = beginColumn;
		t.endColumn = endColumn;

		return t;
	}

	int curLexState = 0;
	int defaultLexState = 0;
	int jjnewStateCnt;
	int jjround;
	int jjmatchedPos;
	int jjmatchedKind;

	/** Get the next Token. */
	public Token getNextToken() {
		Token matchedToken;
		int curPos = 0;

		EOFLoop: for (;;) {
			try {
				curChar = input_stream.BeginToken();
			} catch (java.io.IOException e) {
				jjmatchedKind = 0;
				matchedToken = jjFillToken();
				return matchedToken;
			}

			jjmatchedKind = 0x7fffffff;
			jjmatchedPos = 0;
			curPos = jjMoveStringLiteralDfa0_0();
			if (jjmatchedKind != 0x7fffffff) {
				if (jjmatchedPos + 1 < curPos)
					input_stream.backup(curPos - jjmatchedPos - 1);
				if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
					matchedToken = jjFillToken();
					return matchedToken;
				} else {
					continue EOFLoop;
				}
			}
			int error_line = input_stream.getEndLine();
			int error_column = input_stream.getEndColumn();
			String error_after = null;
			boolean EOFSeen = false;
			try {
				input_stream.readChar();
				input_stream.backup(1);
			} catch (java.io.IOException e1) {
				EOFSeen = true;
				error_after = curPos <= 1 ? "" : input_stream.GetImage();
				if (curChar == '\n' || curChar == '\r') {
					error_line++;
					error_column = 0;
				} else
					error_column++;
			}
			if (!EOFSeen) {
				input_stream.backup(1);
				error_after = curPos <= 1 ? "" : input_stream.GetImage();
			}
			throw new TokenMgrError(EOFSeen, curLexState, error_line,
					error_column, error_after, curChar,
					TokenMgrError.LEXICAL_ERROR);
		}
	}

	private void jjCheckNAdd(int state) {
		if (jjrounds[state] != jjround) {
			jjstateSet[jjnewStateCnt++] = state;
			jjrounds[state] = jjround;
		}
	}

	private void jjAddStates(int start, int end) {
		do {
			jjstateSet[jjnewStateCnt++] = jjnextStates[start];
		} while (start++ != end);
	}

	private void jjCheckNAddTwoStates(int state1, int state2) {
		jjCheckNAdd(state1);
		jjCheckNAdd(state2);
	}

}
