/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
package cn.edu.thss.iise.beehivez.server.index.petrinetindex.relationindex.queryparser;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryParserConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int WHITESPACE = 1;
	/** RegularExpression Id. */
	int EXIST = 2;
	/** RegularExpression Id. */
	int PARALLELWITH = 3;
	/** RegularExpression Id. */
	int EXCLUDE = 4;
	/** RegularExpression Id. */
	int PRECEDE = 5;
	/** RegularExpression Id. */
	int AND = 6;
	/** RegularExpression Id. */
	int OR = 7;
	/** RegularExpression Id. */
	int NOT = 8;

	/** Lexical state. */
	int DEFAULT = 0;

	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "<WHITESPACE>", "\"exist\"",
			"<PARALLELWITH>", "<EXCLUDE>", "<PRECEDE>", "<AND>", "<OR>",
			"<NOT>", "<token of kind 9>", "\";\"", "\"(\"", "\")\"",
			"<token of kind 13>", };

}
